"""the run record and the audit log

Revision ID: 0001
Revises:
Create Date: 2026-09-14 08:53:14.456731
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

import agentic_base.domain.run_record

revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_entry",
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("tenant", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("run_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("event", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "at",
            agentic_base.domain.run_record.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("audit_fields", sa.JSON(), nullable=True),
        sa.Column("previous_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("seq"),
        sa.UniqueConstraint("tenant", "previous_hash"),
    )
    with op.batch_alter_table("audit_entry", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audit_entry_run_id"), ["run_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_entry_tenant"), ["tenant"], unique=False
        )

    op.create_table(
        "run_record",
        sa.Column("run_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "created_at",
            agentic_base.domain.run_record.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("tenant", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("item", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("arm", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "arm_fingerprint", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("system_prompt", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("messages", sa.JSON(), nullable=True),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("endpoint", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("precision", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("code_revision", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("principal", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "classification",
            sa.Enum(
                "unclassified",
                "public",
                "internal",
                "confidential",
                "personal",
                "health",
                name="dataclass",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column(
            "isolation_tier",
            sa.Enum(
                "unspecified",
                "community",
                "virtualised",
                "isolated",
                name="isolationtier",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("redaction", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("disclosure", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "content_marking", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("approvals", sa.JSON(), nullable=True),
        sa.Column("component_versions", sa.JSON(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "completed",
                "failed",
                "infrastructure_error",
                "timeout",
                "cancelled",
                name="runstatus",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("failure_kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=True),
        sa.Column(
            "label_source",
            sa.Enum(
                "unlabelled",
                "self_reported",
                "convenience_verifier",
                "official_harness",
                "benchmark_grader",
                "human",
                "user_feedback",
                "model_judge",
                name="labelsource",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column(
            "labelled_at",
            agentic_base.domain.run_record.UTCDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("degraded", sa.Boolean(), nullable=False),
        sa.Column("instrument", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("joules", sa.Float(), nullable=False),
        sa.Column("num_steps", sa.Integer(), nullable=False),
        sa.Column("total_tool_calls", sa.Integer(), nullable=False),
        sa.Column("elapsed_ms", sa.Float(), nullable=False),
        sa.Column("extra", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("run_id"),
    )
    with op.batch_alter_table("run_record", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_run_record_arm"), ["arm"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_run_record_arm_fingerprint"),
            ["arm_fingerprint"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_run_record_classification"), ["classification"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_run_record_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_run_record_item"), ["item"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_run_record_label_source"), ["label_source"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_run_record_model"), ["model"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_run_record_principal"), ["principal"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_run_record_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_run_record_tenant"), ["tenant"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("run_record", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_run_record_tenant"))
        batch_op.drop_index(batch_op.f("ix_run_record_status"))
        batch_op.drop_index(batch_op.f("ix_run_record_principal"))
        batch_op.drop_index(batch_op.f("ix_run_record_model"))
        batch_op.drop_index(batch_op.f("ix_run_record_label_source"))
        batch_op.drop_index(batch_op.f("ix_run_record_item"))
        batch_op.drop_index(batch_op.f("ix_run_record_created_at"))
        batch_op.drop_index(batch_op.f("ix_run_record_classification"))
        batch_op.drop_index(batch_op.f("ix_run_record_arm_fingerprint"))
        batch_op.drop_index(batch_op.f("ix_run_record_arm"))

    op.drop_table("run_record")
    with op.batch_alter_table("audit_entry", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_entry_tenant"))
        batch_op.drop_index(batch_op.f("ix_audit_entry_run_id"))

    op.drop_table("audit_entry")
    # ### end Alembic commands ###
